### ISSUE TITLE
MBM.py registration with model mask fails where unmasked run succeeds

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#177]
I ran an initial MBM.py with my raw input files to bootstrap a model, it ran file and the resulting average looked good. I then created a rough brain mask for the model and I'm attempting to re-run the MBM.py against the model with mask:
```
MBM.py --queue-type=sge --num-executors=120 --proc=1 --mem=3 \
    --verbose --pipeline-name=male-and-female-raw-masked \
    --lsq6-large-rotations --registration-method=mincANTS --calc-stats \
    --init-model=/data/chamal/projects/gabriel/rat-atlas/model/raw-model.mnc \
    --max-failed-executors 10 \
    --no-monitor-heartbeats \
    /data/chamal/projects/gabriel/rat-atlas/subjects/*.mnc
```

The resulting registrations are terrible with no sensible average produced

I've also tried the run with ``--lsq6-centre-estimation``(fails, can't find center) and ``--lsq6-simple`` (same result as large rotations.

Am I doing something wrong? Perhaps the --lsq6-large-rotations step should be done without a mask?

**Comment by mcvaneede** [comment]
What parameters did you use for your initial MBM.py call? And what kind of data is this -- mouse or human (i.e. what is the resolution)?

**Comment by gdevenyi** [comment]
The original job run (without masks) was:
```
MBM.py --queue-type=sge --num-executors=60 --proc=1 --mem=3 \
    --verbose --pipeline-name=male-and-female-raw \
    --lsq6-large-rotations --registration-method=mincANTS --calc-stats \
    --bootstrap ../subjects/*.mnc
```

These files are rat brains
```
mincinfo RMS.20141213_MCH_RAt001_857_FISP.mnc
file: RMS.20141213_MCH_RAt001_857_FISP.mnc
image: signed__ float 66.4435882568359375 to 22549.599609375
image dimensions: zspace yspace xspace
    dimension name         length         step        start
    --------------         ------         ----        -----
    zspace                    180          0.2            0
    yspace                    180          0.2            0
    xspace                    180          0.2            0

```

**Comment by jasonlerch** [comment]
It might be misfiring on the calculation of blurs (which are determined based on step sizes). Try running it with an explicit lsq6 parameter file; try the example below (paste into text file and call MBM with --lsq6-protocol=)

"blur";1;0.5;0.25
"step";1;1;1
"gradient";FALSE;FALSE;FALSE
"simplex";1;1;1
"w_translations”;0.2;0.2;0.2

**Comment by mcvaneede** [comment]
In that case, it makes sense to combine it with --lsq6-centre-estimation, so you'd get:

MBM.py ... --lsq6-centre-estimation --lsq6-protocol=linear_protocol.csv ...

The assumption being that the files are all roughly oriented in the same way. If large rotations exist between your input files, you could try to use the mouse brain settings instead of basing the parameters on the resolution:

MBM.py ... --lsq6-large-rotations --lsq6-large-rotations-parameters=mousebrain ...

**Comment by gdevenyi** [comment]
I'm still having the same issues, running MBM with a masked model, this time running mice against the c57 atlas model, the lsq6 registration is bad and all subsequent stages and hence bad, I'm running my pipeline line this:
```
MBM.py --num-executors=24 \
    --verbose --pipeline-name=D2KO-all-timepoint \
    --init-model atlas/c57.mnc \
	--lsq6-large-rotations \
    --lsq6-large-rotations-parameters mousebrain \
    --lsq12-subject-matter mousebrain \
    --config-file /project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/config/SciNet.cfg \
    inputs/*.mnc
```

init-model is the c57 mouse atlas + a mask created by merging all the labels

**Comment by gdevenyi** [comment]
Hey, I'm still having this problem in MBM, can you provide any insight?

**Comment by mcvaneede** [comment]
Generally the 6 parameter alignment fails when the model file and the input files are not roughly in the same orientation. The default parameters for rotational minctracc recover about 100 degrees (50 degrees around each of the axis in both directions). So my initial guess is that the positional difference between the model and input files is too large.

Are you running this pipeline at SciNet? Could you maybe point me to one or two of your input files (that fail) and the initial model you are using?

**Comment by gdevenyi** [comment]
To be clear, removing the mask from the MBM runs the lsq6 stage successfully runs, it's when I mask the brain that it fails.

Yes, running on scinet, files are in /scratch/m/mchakrav/gumae/D2KO/inputs and initial model is your c57 atlas in /scratch/m/mchakrav/gumae/D2KO/MBM-all-timepoints/atlas

**Comment by mcvaneede** [comment]
I do not have permission to look at your files. Is there a place you could copy a couple of them to where I can read them?

**Comment by gdevenyi** [comment]
Moved representative files to:
/home/m/mchakrav/gdevenyi/scratch/pydpiper-test-files

Should be readable by other and read+write by your scinet username.

**Comment by mcvaneede** [comment]
I ran two LSQ6 registrations on your data:

1) without a mask
LSQ6.py  \
--lsq6-target c57_140micron.mnc \
--lsq6-large-rotations \
--lsq6-large-rotations-parameters mousebrain  \
... RMS.20141029_BGI_D2K0*mnc

2) with the mask in an initial model:
LSQ6.py \
--init-model  init-model-140micron/c57.mnc \
--lsq6-large-rotations \
--lsq6-large-rotations-parameters mousebrain  \
... RMS.20141029_BGI_D2K0*mnc

I changed the resolution of the c57 files to be 140 micron, because MBM (and LSQ6) base the resolution of all files produced in the pipeline on the target. If that is 30 micron, you would actually be upsampling all your data, which would greatly increase the amount of computing time and memory used.

In my registrations neither are really good, but the one without the mask is indeed better. The reason that neither of them do well, is because the rotational (positional) difference between the input files and the c57.mnc file is larger than 50 degrees in all directions. This is the default range along which rotational minctracc does its brute force search around each axis. In the unmasked registration, all files are actually registered "backwards" (olfactory bulbs aligned to the cerebellum from the target), because that is the best alignment possible given the default rotational range. The reason that this works better without a mask, is because the mask is very tight. Using a blurred version of the entire brain/surrounding tissue provides a better shape to match, than limiting the field of view using that tight mask.

What I would do is either create a "native" c57 brain which is oriented in the same was as your input brains, and provide the initial model with those and a 6 parameter transformation that brings that native file to standard space. I would also dilate the mask for the native file a fair bit. Only after your files have been roughly aligned, is a snug mask appropriate. So your initial model would then have:
c57.mnc
c57_mask.mnc
c57_native.mnc (oriented like the input files)
c57_native_mask.mnc (dilated)
c57_native_to_standard.xfm (6 parameter transform to c57.mnc)

The other option would be to increase the range for rotational minctracc:
--lsq6-rotational-range 180
--lsq6-rotational-interval 10 (or 20)

However that will hugely increase the computation time for that stage. In that case you could keep the same orientation for the c57 brain (and you would simply need an identity transformation), but I would still dilate the mask:
c57.mnc
c57_mask.mnc
c57_native.mnc (same as c57.mnc)
c57_native_mask.mnc (dilated)
c57_native_to_standard.xfm (identity transform)

**Comment by gdevenyi** [comment]
Thanks @mcvaneede ! I didn't know pydpiper based the pipeline resolution on the model that is definitely having a huge impact on performance!

I will resample my atlas to the same resolution as the input files and I will generate the "native" version as you suggested.

I had generated the mask file using
```
mincmorph -clobber -successive 'B[0.5:999]DDDDDDDDDDDDEEEEEE' c57_fixed_labels_resized.mnc c57_mask.mnc
```
For the generous mask, should I remove the erosions and use that resulting mask?

This brings me to my first comment where I was initially running into this bug, in that case (comment 1) the model and brains are in the same space, since the bootstrap of the subjects generated the model, any thoughts on why that problem is happening? That was run on an earlier version of pydpiper so it may be I need to re-test...

**Comment by mcvaneede** [comment]
I've run some tests with a larger mask, and the following worked for me:
```
mincmorph -clobber -successive 'B[0.5:999]DDDDDDDDDDDDDDDDDDDD' c57_fixed_labels_resized.mnc c57_larger_mask.mnc
```
Then, I ran a registration without creating a proper native file, but allowing a larger range for rotational minctracc (this took about an hour and a half instead of 30 minutes). Now, the LSQ6 registration works perfectly:
```
LSQ6.py \
--init-model init-model-140micron-large-mask/c57.mnc \
--lsq6-large-rotations \
--lsq6-large-rotations-parameters mousebrain \
--lsq6-rotational-range 180 \
--lsq6-rotational-interval 20 \
... RMS.20141029_BGI_D2K0*mnc
```

As to your follow-up question. When I run a registration with a large enough range for rotational minctracc, but with a very snug mask, the alignment still fails. So my guess to the initial issue might have been related to the mask. Give it a try with a larger mask, and see if that solves the issue.

**Comment by gdevenyi** [comment]
Resolved as being an issue with "large rotations" not being large enough.
