### ISSUE TITLE
BUG: pydpiper should rely on the existence of files to check status of pipeline

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#187]
If the completed stages file is modified, damaged or lost, the whole pipeline would need to rerun, the pipeline should check the status of files to determine which stages need to be run.

**Comment by bcdarwin** [comment]
We used to have such a feature, but removed it because we couldn't guarantee that existing files weren't corrupt in some way, whereas the completed stages file is in some sense 'atomic' (once an index is written to this file, the relevant files are fully written out, although we still have to worry about files becoming corrupted later, such as by executors which keep running after losing contact with the server....).

Perhaps the right thing to do is create a subdirectory for each 'run' of the pipeline such that simply runnning a Pydpiper command in a directory wouldn't touch any files from a previous run without explicitly pointing to a set of files to restart from, i.e., each run would be in some sense 'pure'.  Some other modern pipelining systems do this.

Slightly related: might be worthwhile checksumming output files as well as inputs (see #51).

**Comment by gdevenyi** [comment]
CIVET creates a .failed or .finished logfile on a per-stage basis in subject directories.

I think files + md5sum is an excellent way to verify integrity.

**Comment by bcdarwin** [comment]
So one current issue is that Pydpiper must erase its state at each startup since stage hashes are computed only from the command.  If we computed hashes transitively from all ancestors, we wouldn't have this problem and could have an append-only log of finished stages.  One downside is that it would be a bit harder to figure out which hash corresponds to which command (currently you just hash the command), but we could write the extra data to disk.  (A more database-like way of storing/querying/modifying state and logging events would be very useful.)

Indeed, recording checksums of files as they finish would be useful as well.

**Comment by gdevenyi** [comment]
Reasonably handled now by:
  --check-input-files \
  --check-outputs \
and --smart-restart
