### ISSUE TITLE
v1.18 specifies ConfigArgParse version which doesn't exist

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#247]
setup.py says:
ConfigArgParse>0.10.0
Should say:
ConfigArgParse>=0.10.0

**Comment by bcdarwin** [comment]
Unfortunately that's not a mistake - ConfigArgParse 0.10.0 had some weird bugs which under some conditions caused flags not be set incorrectly.  That's only fixed in their develop.  I've filed an issue asking for a new release ...

Technically you're right in that I could specify the github url in `setup.py` though ...

**Comment by gdevenyi** [comment]
Hi, any movement on this? MINC-VM build is broken with this release included.

**Comment by bcdarwin** [comment]
Looks like the configargparse maintainer hasn't responded, so tomorrow I'll just add the github dependency to pydpiper.

________________________________

**Comment by bcdarwin** [comment]
New tag pushed.

**Comment by gdevenyi** [comment]
Thanks, v1.18.1 now in MINC-VM and build successful.
