### ISSUE TITLE
MAGeT with ANTs?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#257]
We have a dataset where the subjects and an atlas that come from different contrasts. minctracc fails spectacularly on this. I've previously had ANTs do okay with this on human data, is there a nlin file around for MAGeT to run mincANTS instead of minctracc?

Thanks!

**Comment by bcdarwin** [comment]
So Pydpiper 1.x isn't great for this since it was explicitly assumed that only one generation of mincANTS parameters would be needed for template registrations!  We'll release Pydpiper 2 this week, which doesn't have this problem.  I guess you could just start with the usual mincANTS protocol ...

**Comment by gdevenyi** [comment]
Hi,

So it turns out have a NFSv4+ZFS+python3 issue which prevents me to install pydpiper2 right now.

Can you elaborate on the "100x100x100x150 in the first generation ..."?

**Comment by bcdarwin** [comment]
In the example mincANTS protocol file you'll see a line like

"iterations";"100x100x100x0";"100x100x100x40";"100x100x100x150" .

I.e., building the new average proceeds in three stages or 'generations', each using mincANTS at three/four different resolutions.  However, since the MAGeT registrations are simple source-to-target registrations rather than a hierarchical procedure, only the first of these gets used, so you could just change it to x150 and delete the others.  Let me know if you have any problems.


Ben

________________________________

**Comment by gdevenyi** [comment]
Cheers, I think I've got that. I'll give it a try.
