### ISSUE TITLE
Docs for atlas naming for pydpiper2.0?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#270]
I'm again at a loss of what the naming is for input files, now at least, I get a sensible error:

```
ValueError: atlas filename conventions are wrong for atlas '/opt/quarantine/resources/DSUR_2016/pydpiper/DSUR_40micron_native'

```

**Comment by bcdarwin** [comment]
<name>{_average.mnc,_labels.mnc,_mask.mnc}

Sorry, I'll add this to the help message.

**Comment by gdevenyi** [comment]
*if* this could be uniformized with the init-model I could point a single directory for all runs.

**Comment by bcdarwin** [comment]
I think that might work: you can actually drop the _average

**Comment by gdevenyi** [comment]
I had that although it might've been a problem with my "_native" images in the directory. The error doesn't give that much detail.

**Comment by bcdarwin** [comment]
However, in the future we'll take masks from the atlas rather than the initial model, which is important since tighter masks should be used for later parts of the pipeline (this is important for FDR, but we've also found it can matter for lin_from_nlin ...) but LSQ6 wants a looser mask.  We could have _initial_mask and _mask or similar.

**Comment by bcdarwin** [comment]
Ah, you're right.  It'll be fixed ...

**Comment by gdevenyi** [comment]
Cheers. Test run going now.
