### ISSUE TITLE
setenv in jobfiles is a C-shell-ism but used in a bash jobfile

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#289]
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/3e942d0b775aebf5cfbde44bacabae63c12bfd28/pydpiper/execution/pipeline_executor.py#L387

Results in
```
/opt/sge/default/spool/cicws27/job_scripts/1026158: line 3: setenv: command not found
```

In executor logs

**Comment by gdevenyi** [comment]
https://askubuntu.com/questions/484569/how-can-i-fix-setenv-command-not-found-error-ubuntu-12-04-4

**Comment by bcdarwin** [comment]
I did this on purpose, sort of.  The problem is that we have a silly /etc/profile.d/ file around which trashes LD_LIBRARY_PATH, etc., and I don't know how to tell the bash that runs the jobfile not to run this file.  As it turns out, our SGE's default shell is csh.  I was surprised this didn't bite people earlier ...

**Comment by bcdarwin** [comment]
I guess I can switch to bash and change our site config -- but bash probably shouldn't re-run its startup scripts here since we're already sending the whole environment ... ?

**Comment by gdevenyi** [comment]
It doesn't seem to cause any brokenness for me, other than the pyro logfile not being put in the right place.

**Comment by bcdarwin** [comment]
That should be its only effect.

**Comment by bcdarwin** [comment]
We no longer use SGE or assume csh anywhere.
