### ISSUE TITLE
pydiper MAGeT feature request - lsq12 stage

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#317]
I'd like to use pydpiper for a rat developmental project but due to the fairly large differences in brain size due to age, MAGeT fails pretty spectacularly.

This could be remedied by adding a LSQ12 stage to MAGeT (as is done in the human version).

**Comment by bcdarwin** [comment]
MAGeT already has this -- are you using an lsq12 protocol appropriate for rats?

**Comment by bcdarwin** [comment]
More precisely each nonlinear registration is preceded by an LSQ12 one -- there is no alignment to a consensus "LSQ12 space".

**Comment by gdevenyi** [comment]
Okay, the outputs I get look to me like a failure to effectively scale the brains to the atlas before non-linear registration.

I would have expected that if MBM works for this population of rats using the default setting, that MAGeT would as well.

I guess not.

I haven't tested the exact settings in #309 for this population, so I'll try that.

**Comment by bcdarwin** [comment]
Ah, interesting.  While MBM does an iterative LSQ12 procedure before nonlinear alignment, MAGeT just does lsq12+nlin between each pair of images.  I guess that even if some LSQ12 registrations initially fail due to size differences in MBM you'll probably still get out of this trap eventually due to the averaging.  So MAGeT is indeed probably worse at overcoming such differences.

________________________________
