### ISSUE TITLE
2.0.6 doesn't parse MAGeT atlas directory properly

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#323]
```sh
> ls atlas
thisisanatlas_average.mnc  thisisanatlas_labels.mnc  thisisanatlas_mask.mnc

> MBM.py <options>
<CLIP>
ValueError: atlas filename conventions are wrong for atlas 'atlas/thisisanatl'
```

**Comment by bcdarwin** [comment]
The problem is in `MAGeT.py`:

```
90       base = filename.rstrip(suffix)
```

`rstrip` doesn't work like `bash`'s `basename` but instead removes any character in the given "set" (here `suffix`).

Temporary workaround: rename your atlases to something that doesn't end in characters appearing in "average", "labels", "mask" ... ours are mostly numbers (years or versions).
