### ISSUE TITLE
Update mincANTS atom to use the automatically generated inverse transform

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#81]
Because it is diffeomorphic, mincANTS calculates both the forward and inverse transforms for any registration between two files. We should exploit this in the atom when file handlers are used, to set the last transform between target and input to be this inverse. 

This will save pipeline stages down the road, as inverses are often necessary for transform concatenation and statistical purposes.

**Comment by bcdarwin** [comment]
In the modern setting, there's no generic way of getting the 'last transform' between two files (this notion is not even well-defined).  One could imagine returning the inverse transform from various pieces of code, but this complicates things since now mincANTS-based code will return more information than minctracc-based code, and hiding this from the programmer could be annoying and overcomplicated.  Closing for now since computing inverses isn't expensive and I don't have any arguments for why doing so should be much worse from a numerical perspective.

**Comment by gdevenyi** [comment]
Going forward,  the diffomorphosms from antsRegistration don't have a defined way to compute their inverse.

**Comment by bcdarwin** [comment]
I'm confused ... you mean antsRegistration doesn't have an option to output the automatically computed inverse?

**Comment by gdevenyi** [comment]
No, it automatically does.

I mean that post-computation of the inverse from the forward transform isn't possible (compared to minctracc, where it is).

**Comment by bcdarwin** [comment]
If the transform is a diffeomorphism, how is that possible?
